---
- name: '004 | AUDIT | Disallow logging in with empty password by SSH'
  command: "grep -q '^PermitEmptyPasswords yes' /etc/ssh/sshd_config"
  register: sshd_empty_passwords
  changed_when: false
  always_run: true
  failed_when: sshd_empty_passwords.rc == 2
  tags:
    - audit

- name: '004 | PATCH | Disallow logging in with empty password by PAM'
  lineinfile:
    dest: /etc/ssh/sshd_config
    line: 'PermitEmptyPasswords no'
    verify: '/usr/sbin/sshd -T -f %s > /dev/null'
  when: '{{ sshd_empty_passwords.rc != 0 }}'
  notify: 'Restart sshd'
  tags:
    - patch
