---
- name: '019 | AUDIT | Disable accepting source routed IP packets'
  shell: "sysctl net.inet.ip.accept_sourceroute | awk -F: '{print $2 }' "
  register: accept_sourceroute
  changed_when: false
  always_run: yes
  tags:
    - audit

- name: '019 | PATCH | Diable accepting source routed IP packets'
  sysctl:
    name: 'net.inet.ip.accept_sourceroute'
    value: 0
    state: present
    reload: yes
  when:
    - "'unknown oid' not in accept_sourceroute.stderr"
    - 'accept_sourceroute.stdout != 0'
  tags:
    - patch
