---
- name: '022 | AUDIT | Do not send ABORT on segments to closed SCTP ports'
  shell: "sysctl net.inet.sctp.blackhole | awk -F: '{print $2 }' "
  register: sctp_blackhole
  changed_when: false
  always_run: yes
  tags:
    - audit

- name: '022 | PATCH | Do not send ABORT on segments to closed SCTP ports'
  sysctl:
    name: 'net.inet.sctp.blackhole'
    value: 2
    state: present
    reload: yes
  when:
    - '{{ sctp_blackhole.stdout }} != 2'
    - 'not "unknown oid" in {{ sctp_blackhole.stderr }}'
  tags:
    - patch
