---
- name: '025 | AUDIT | Do not accept ICMPv6 redirect messages'
  shell: "sysctl net.inet6.icmp6.rediraccept | awk -F: '{print $2 }' "
  register: icmp6_rediraccept
  changed_when: false
  always_run: yes
  tags:
    - audit

- name: '025 | PATCH | Do not accept ICMPv6 redirect messages'
  sysctl:
    name: 'net.inet6.icmp6.rediraccept'
    value: 0
    state: present
    reload: yes
  when:
    - "'unknown oid' not in icmp6_rediraccept.stderr"
    - '{{ icmp6_rediraccept.stdout }} != 0'
  tags:
    - patch
